//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;
using System;

[assembly: AssemblyTitle("Cake.Stylelint")]
[assembly: AssemblyDescription("Cake Stylelint AddIn")]
[assembly: AssemblyCompany("Cake Contributions")]
[assembly: AssemblyProduct("Cake.Stylelint")]
[assembly: AssemblyVersion("0.1.0")]
[assembly: AssemblyFileVersion("0.1.0")]
[assembly: AssemblyInformationalVersion("0.1.0")]
[assembly: AssemblyCopyright("Copyright © Cake Contributions 2019 - Present")]
[assembly: CLSCompliant(true)]
